### PR TITLE
configs: Fix typo in pjsip.conf.sample.

### PR DESCRIPTION
**Pull request by solaechea**
Minor syntax error

### CODE REVIEW

**Review by InterLinked1 — CHANGES_REQUESTED** [review]
CLA is not signed, and commit message should be formatted to comply with the commit message guidelines, even something as simple as:

configs: Fix typo in pjsip.conf.sample.

This should be cherry picked to 18, 20, and 21.

**Comment by gtjoseph** [comment]
REMINDER: If this PR applies to other branches, please add a comment with the appropriate "cherry-pick-to" headers as per the [Create a Pull Request](https://docs.asterisk.org/Development/Policies-and-Procedures/Code-Contribution/) process.  

If you don't want it cherry-picked, please add a comment with `cherry-pick-to: none` so we don't keep asking.

If, after adding "cherry-pick-to" comments, you change your mind, please edit the comment to DELETE the header lines and add `cherry-pick-to: none`.

The currently active branches are now __18, 20, 21 and master__.

**Comment by solaechea** [comment]
cherry-pick-to: 21
cherry-pick-to: 20
cherry-pick-to: 18
cherry-pick-to: master

**Comment by InterLinked1** [comment]
> cherry-pick-to: 21 cherry-pick-to: 20 cherry-pick-to: 18 cherry-pick-to: master

It doesn't need to be cherry picked to master, since that's where it's being merged to.

**Review by jcolp — APPROVED** [review]

**Pull request merged**
