### PR TITLE
res_pjsip_pubsub: Persist subscription 'generator_data' in sorcery

### LINKED ISSUE #895: [bug]: PostgreSQL RealTime: Failed to query ‘ps_subscription_persistence@asterisk’.
### Severity

Trivial

### Versions

21.4.3

### Components/Modules

ps_subscription_persistence

### Operating Environment

Linux asterisk-node-01 6.1.0-25-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.106-3 (2024-08-26) x86_64 GNU/Linux

### Frequency of Occurrence

Constant

### Issue Description

Created database for realtime PJSIP over `alembic` and handle next issue:

```
ERROR: column “generator_data” of relation “ps_subscription_persistence” does not exist
```

At `res_pgsql.conf` I'm set `requirements = createclose` but this doen’t help.

Then I'm created this column manually and issue was resolved.

**Dear support team, coud you add this to new release `alembic`.**

### Relevant log output

```shell
[Sep 23 09:59:35] ERROR[3315]: res_config_pgsql.c:167 _pgsql_exec: PostgreSQL RealTime: Failed to query ‘ps_subscription_persistence@asterisk’.
[Sep 23 09:59:35] ERROR[3315]: res_config_pgsql.c:168 _pgsql_exec: PostgreSQL RealTime: Query Failed: INSERT INTO ps_subscription_persistence (id, src_port, expires, transport_key, cseq, prune_on_boot, endpoint, generator_data, packet, src_name, local_name, tag, contact_uri, local_port) VALUES (‘ade0a37f-0ecd-4b17-a715-d9d8ebc39e28’, ‘0’, ‘0’, ‘0’, ‘0’, ‘no’, ‘1102’, ‘’, ‘’, ‘’, ‘’, ‘663677af-f2dc-44e4-af30-a3a647131f03’, ‘’, ‘0’)
[Sep 23 09:59:35] ERROR[3315]: res_config_pgsql.c:169 pgsql_exec: PostgreSQL RealTime: Query Failed because: ERROR: column “generator_data” of relation “ps_subscription_persistence” does not exist
LINE 1: …es, transport_key, cseq, prune_on_boot, endpoint, generator…
                                                           ^
(PGRES_FATAL_ERROR)

...

[Sep 23 09:59:35] NOTICE[3315] res_config_pgsql.c: Attempted to update column ‘generator_data’ in table ‘ps_subscription_persistence’, but column does not exist!
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

### PR DESCRIPTION
**Pull request by seanbright**
Fixes #895

### CODE REVIEW

**Comment by seanbright** [comment]
cherry-pick-to: 18
cherry-pick-to: 20
cherry-pick-to: 21
cherry-pick-to: 22

**Review by jcolp — APPROVED** [review]

**Comment by gtjoseph** [comment]
@seanbright Can you check if the PR applies to certified/20.7 and certified/18.9?  It'd be nice to keep them on par with the base branches so future cherry-picks are easier.  certified/20.7 would be more important than certified/18.9

**Comment by seanbright** [comment]
> @seanbright Can you check if the PR applies to certified/20.7 and certified/18.9?

It does because tenant id was the most recent alembic changes to those branches. I've updated the `cherry-pick-to`s.

**Comment by gtjoseph** [comment]
Thanks!

**Pull request merged**
