### PR TITLE
res_musiconhold: avoid moh state access on unlocked chan

### PR DESCRIPTION
**Pull request by mbradeen**
Move channel unlock to after moh state access to avoid
potential unlocked access to state.

Resolves: #133

### CODE REVIEW

**Comment by mbradeen** [comment]
cherry-pick-to: 20
cherry-pick-to: 18
cherry-pick-to: certified/18.9

**Review by jcolp — DISMISSED** [review]

**Review by seanbright — CHANGES_REQUESTED** [review]
Can you describe - ideally in both a code comment and the commit message - what this is accomplishing? It's not clear to me how the channel lock and the what `state` are related.

**Comment by mbradeen** [comment]
`ast_channel_music_state` returns `chan->music_state`.  One of our partners ran into issues on their live systems.

**Review by seanbright — CHANGES_REQUESTED** [review]
I _think_ you are saying that the channel lock is being used to protect `state` so you have to hold the channel lock while reading/writing to it.

Unfortunately there are numerous places where unprotected access to `state` occurs throughout the file (including a couple times near the top of the same function you are updating).

The [documentation in `channel.h`](https://github.com/asterisk/asterisk/blob/e0ed0db41f32a47b49a655c737b93f66b292cb04/include/asterisk/channel.h#L4103) indicates that the channel must be locked before `ast_channel_music_state(...)` is called which is not occurring in many places throughout this file.

A potential resolution is to give `struct moh_files_state` its own mutex instead of relying on the channel lock. You would still need to take the channel lock when calling `ast_channel_music_state(...)` and `ast_channel_music_state_set(...)` but any manipulation of the state itself could be down under its own lock.

**Comment by seanbright** [comment]
(as an aside it would still be great to understand what this is actually intended to fix)

**Comment by jcolp** [comment]
> I _think_ you are saying that the channel lock is being used to protect `state` so you have to hold the channel lock while reading/writing to it.
> 
> Unfortunately there are numerous places where unprotected access to `state` occurs throughout the file (including a couple times near the top of the same function you are updating).
> 
> The [documentation in `channel.h`](https://github.com/asterisk/asterisk/blob/e0ed0db41f32a47b49a655c737b93f66b292cb04/include/asterisk/channel.h#L4103) indicates that the channel must be locked before `ast_channel_music_state(...)` is called which is not occurring in many places throughout this file.
> 
> A potential resolution is to give `struct moh_files_state` its own mutex instead of relying on the channel lock. You would still need to take the channel lock when calling `ast_channel_music_state(...)` and `ast_channel_music_state_set(...)` but any manipulation of the state itself could be down under its own lock.

Channel is locked when all generator callbacks are invoked, except for generate (which is on purpose according to a comment in the generator API code). That's why there is some locking in the generate callback. The other cases of starting/stopping MOH also have locking since they're outside of generator land, and appear to do it correctly.

**Comment by seanbright** [comment]
OK so it is just the two cases of missing locks at the beginning of `moh_files_generator(...)` that need to be addressed.

**Comment by mbradeen** [comment]
waiting on feedback from original reporter.

**Review by jcolp — APPROVED** [review]

**Comment by mbradeen** [comment]
Example output:
`=======================================================================
=== GIT-master-4099f965e1M
=== Currently Held Locks at Time: 468334:09:29.088484 =================
=======================================================================
===
=== <pending> <lock#> (<file>): <lock type> <line num> <function> <lock name> <lock addr>
=== <locked at>, <failed at>, <held for> (attempts, times locked)
===
=== Thread ID: 0x7f8bff3ca700 LWP:30685 (lock_thread          started at [   83] test_named_lock.c named_lock_test())
=== ---> Lock #0 (test_named_lock.c): MUTEX 49 lock_thread lock 0x7f8c00004ef0
===      468334:09:29.088294, 00:00:00.000000, 00:00:00.000251 (1, 1)
	asterisk __ast_pthread_mutex_lock()
	asterisk __ao2_lock()
	[0x7f8c8dc3a449] test_named_lock.so test_named_lock.c:50 lock_thread()
	asterisk <unknown>()
	[0x7f8cd707b609] libpthread.so.0 pthread_create.c:478 start_thread()
	[0x7f8cd6cb4133] libc.so.6 :0 clone()
=== -------------------------------------------------------------------
===
=== Thread ID: 0x7f8bff34d700 LWP:30686 (lock_thread          started at [   84] test_named_lock.c named_lock_test())
=== ---> Lock #0 (test_named_lock.c): MUTEX 49 lock_thread lock 0x7f8c0c005070
===      468334:09:29.089931, 00:00:00.000000, 00:00:00.026615 (1, 1)
	asterisk __ast_pthread_mutex_lock()
	asterisk __ao2_lock()
	[0x7f8c8dc3a449] test_named_lock.so test_named_lock.c:50 lock_thread()
	asterisk <unknown>()
	[0x7f8cd707b609] libpthread.so.0 pthread_create.c:478 start_thread()
	[0x7f8cd6cb4133] libc.so.6 :0 clone()
=== -------------------------------------------------------------------
===
=======================================================================
`

**Comment by seanbright** [comment]
So `moh_files_generator(...)` is the only function that reads/writes to the `sample_queue` member of `struct moh_files_state` so do we actually need it as part of the struct or can we just use a local variable in that function? That would simplify the locking a bit if that is the case.

**Comment by jcolp** [comment]
> So `moh_files_generator(...)` is the only function that reads/writes to the `sample_queue` member of `struct moh_files_state` so do we actually need it as part of the struct or can we just use a local variable in that function? That would simplify the locking a bit if that is the case.

I believe it exists on state such that if the returned frame has a greater number of samples than is currently needed, it tries its best to not produce more on the next invocation. For example the generator is asked for 160 samples but gets back 320 samples, the next invocation then becomes a noop if 160 is requested again.

I'm not sure this happens in practice (though it may depending on underlying codecs).

**Comment by seanbright** [comment]
> > So `moh_files_generator(...)` is the only function that reads/writes to the `sample_queue` member of `struct moh_files_state` so do we actually need it as part of the struct or can we just use a local variable in that function? That would simplify the locking a bit if that is the case.
> 
> I believe it exists on state such that if the returned frame has a greater number of samples than is currently needed, it tries its best to not produce more on the next invocation. For example the generator is asked for 160 samples but gets back 320 samples, the next invocation then becomes a noop if 160 is requested again.
> 
> I'm not sure this happens in practice (though it may depending on underlying codecs).

The only nominal way out of `moh_files_generate(...)` is with `state->sample_queue` being `0` (or less than `0`). If we leave for any other reason (`return -1`) the generator is stopped, so there wouldn't be a subsequent invocation.

**Comment by jcolp** [comment]
> > > So `moh_files_generator(...)` is the only function that reads/writes to the `sample_queue` member of `struct moh_files_state` so do we actually need it as part of the struct or can we just use a local variable in that function? That would simplify the locking a bit if that is the case.
> > 
> > 
> > I believe it exists on state such that if the returned frame has a greater number of samples than is currently needed, it tries its best to not produce more on the next invocation. For example the generator is asked for 160 samples but gets back 320 samples, the next invocation then becomes a noop if 160 is requested again.
> > I'm not sure this happens in practice (though it may depending on underlying codecs).
> 
> The only nominal way out of `moh_files_generator(...)` is with `state->sample_queue` being `0` (or less than `0`). If we leave for any other reason (`return -1`) the generator is stopped, so there wouldn't be a subsequent invocation.

Right, in the case I mentioned state->sample_queue would go negative.

**Comment by jcolp** [comment]
I've given this some further thought and I think we should keep sample_queue on state to cover the scenario I mentioned, I'm not comfortable making it local and potentially changing that behavior for some people and causing unintendend consequences.

**Review by seanbright — APPROVED** [review]

**Review by gtjoseph — APPROVED** [review]

**Pull request merged**
