### PR TITLE
TLS in asterisk currently does not accept wildcarded DN's when connecting

### PR DESCRIPTION
**Pull request by dirkx**
TLS  currently does not accept wildcarded DN's when connecting to a TLS/SSL host. This tweak makes that work. Fixes/addresses issue  #269

### CODE REVIEW

**Review by InterLinked1 — CHANGES_REQUESTED** [review]
chan_sip no longer accepts changes here. Is this applicable to anything else that would merit its inclusion? If so, the commit message should be framed as such.

This PR currently has 2 PRs that need to be squashed together.

There are some coding guideline violations that need to be addressed as well.

The existing commit message does not comply with the commit message guidelines.

**Review by seanbright — CHANGES_REQUESTED** [review]
This code will allow `*.example.com` to match `any.number.of.subdomain.labels.example.com` which is incorrect.

**Comment by asteriskteam** [comment]
This PR has been marked stale because it has been in "Changes Requested" or "submitter-action-required" state for 28 days or more. Please make the requested changes within 14 days or the PR will be closed.

**Comment by asteriskteam** [comment]
This PR has been closed because it has been in "Changes Requested" or "submitter-action-required" state for more than 42 days.

**Pull request closed without merging**
