### PR TITLE
app_speech_utils.c: Allow partial speech results.

### PR DESCRIPTION
**Pull request by chrsmj**
Adds 'p' option to SpeechBackground() application.
With this option, when the app timeout is reached,
whatever the backend speech engine collected will
be returned as if it were the final, full result.
(This works for engines that make partial results.)

Resolves: #572

UserNote: The words might be less than the best.

### CODE REVIEW

**Comment by gtjoseph** [comment]
You need to sign the CLA.  Click on the "Details" link in the license/cla line in the checks list above.

**Comment by jcolp** [comment]
@gtjoseph It is signed, not sure why it is not showing up on here.

**Comment by gtjoseph** [comment]
> @gtjoseph It is signed, not sure why it is not showing up on here.

Bah.

**Review by jcolp — CHANGES_REQUESTED** [review]
The UserNote is what gets placed into release notes. As it is, it gives no indication as to what it is referring to or what it means. It needs to be specific, for example:

"The SpeechBackground dialplan application now supports a 'p' optional that will return partial results from speech engines that provide them when a timeout occurs."

**Comment by chrsmj** [comment]
cherry-pick-to: 21
cherry-pick-to: 20
cherry-pick-to: 18
cherry-pick-to: certified/18.9

**Review by jcolp — APPROVED** [review]

**Pull request merged**
