### PR TITLE
core: Cleanup gerrit and JIRA references.

### PR DESCRIPTION
**Pull request by seanbright**
Resolves: #39

### CODE REVIEW

**Comment by seanbright** [comment]
cherry-pick-to: 20
cherry-pick-to: master

**Review by jcolp — APPROVED** [review]

**Review by gtjoseph — CHANGES_REQUESTED** [review]
The .gitreview file is used by build_tools/make_version and the build scripts to determine the base branch so we still need it.  We could remove the gerrit references though...
```
[github]
defaultbranch=master
basebranch=master
```
Or we could find another way to determine base branch.

**Comment by jcolp** [comment]
We haven't had .gitreview since the beginning of Gerrit, it was added afterwards, so how was it done before?

**Comment by gtjoseph** [comment]
> We haven't had .gitreview since the beginning of Gerrit, it was added afterwards, so how was it done before?

The build/install/test processes were much simpler back then and didn't need to know the base branch.  One way we use it today is to determine which builds of the external codecs and DPMA to download (or NOT download in case of master).

**Comment by jcolp** [comment]
According to the git log it did know the base branch back then, @matt-jordan hardcoded it in instead of parsing it out of .gitreview at the time. Our use of things got more "fancy" afterwards.

**Comment by gtjoseph** [comment]
Well, however we determine it, we still need to know and the scripts need to be changed accordingly.

**Comment by seanbright** [comment]
New proposal is that we put it in configure.ac and pull it from there if needed.

**Review by jcolp — APPROVED** [review]
I'm down with this approach.

**Comment by seanbright** [comment]
> You need to run bootstrap.sh to update ./configure.
> Actually creating new variable for this and exporting it to makeopts.in and autoconfig.in, etc. would make things easier in the future.

I will run bootstrap, this was just to propose the approach. 

I’m pretty sure there is already a `PACKAGE_VERSION` variable that ends up in `autoconfig.h` but I will confirm.

**Review by jcolp — APPROVED** [review]

**Comment by gtjoseph** [comment]
Feel free to do the other branches.

**Comment by seanbright** [comment]
> Feel free to do the other branches.

[done](https://github.com/asterisk/asterisk/pull/57) and [done](https://github.com/asterisk/asterisk/pull/58).

**Pull request merged**
