### PR TITLE
Remove UPGRADE.txt and CHANGES

### PR DESCRIPTION
**Pull request by intellasoft**
Fixes: #360

### CODE REVIEW

**Comment by kobaz** [comment]
cherry-pick-to: 20
cherry-pick-to: 18

**Review by gtjoseph — DISMISSED** [review]
Actually, these 2 files need to be deleted as they are no longer even updated. :)

**Comment by kobaz** [comment]
For historical/handyness purposes would it be applicable to add back in the updates to those files instead?

**Comment by jcolp** [comment]
What updates are you referring to? The release process creates a CHANGES.md in releases.

**Comment by kobaz** [comment]
I was referring to the base file called CHANGES which has instructions that point to a file that no longer exists as well as UPGRADE.txt which has instructions that point to a file that no longer exists


There is no CHANGES.md file so far that I can see that's part of the git repo in master.  And the only changes related files that exist, appear to be the old 'CHANGES" file.  There is however a CHANGES.md file in branch 18 for example.

**Comment by jcolp** [comment]
Okay, but what does this mean:

"For historical/handyness purposes would it be applicable to add back in the updates to those files instead?"

Add back in what updates to what files

**Comment by jcolp** [comment]
The files themselves are no longer used as George mentioned, and this is a git repo so we can always go back to examine past history if need be. I don't see why they need to remain.

**Comment by seanbright** [comment]
This PR should be updated to delete the files as mentioned by @gtjoseph or it should be closed

**Comment by kobaz** [comment]
Done

**Review by jcolp — APPROVED** [review]

**Comment by gtjoseph** [comment]
Git doesn't like cherry-picking to delete files when when file contents differ.  Once the master and 21 versions merge, I'll manually merge the 20 and 18 versions.

**Pull request merged**
