### PR TITLE
app_voicemail: Fix for loop declarations

### PR DESCRIPTION
**Pull request by mbradeen**
Resolve for loop initial declarations added in cli changes.

Resolves: #275

### CODE REVIEW

**Comment by mbradeen** [comment]
cherry-pick-to: 21
cherry-pick-to: 20
cherry-pick-to: 18
cherry-pick-to: certified/18.9

**Comment by InterLinked1** [comment]
I'm kind of curious, shouldn't 48c6e3fb1da06b8e76a73a4d9099f33664b4b372 have initially caused the build tests to fail? I thought they were built in developer mode, which would catch these types of things and make the warnings errors? Did the CI change when it moved to GitHub?

**Comment by jcolp** [comment]
Even in developer mode it depends on the compiler version. For example, it's not a problem on my system.

**Comment by gtjoseph** [comment]
> I'm kind of curious, shouldn't [48c6e3f](https://github.com/asterisk/asterisk/commit/48c6e3fb1da06b8e76a73a4d9099f33664b4b372) have initially caused the build tests to fail? I thought they were built in developer mode, which would catch these types of things and make the warnings errors? Did the CI change when it moved to GitHub?

I'm going to take a look at the test build options to see if we can catch these.

**Pull request merged**
