### PR TITLE
app_voicemail: Add Variable when VM Box is full

### PR DESCRIPTION
**Pull request by pitzkey**
Addresses #608

### CODE REVIEW

**Review by InterLinked1 — CHANGES_REQUESTED** [review]
Any added variables should have documentation.

Also, I feel like it would make more sense to add this to VM_INFO, so you could check both before and after, but I don't feel as strongly about that.

**Review by gtjoseph — CHANGES_REQUESTED** [review]
Things to do...

- [x] If not a trivial change (typo, documentation correction, etc) open an issue describing the problem.
- [ ] Sign the Contributor License Agreement.
- [ ] Squash commits into a single one.
- [ ] Make sure the PR description and commit message reference the issue. See [Commit Messages](https://docs.asterisk.org/Development/Policies-and-Procedures/Commit-Messages/)
- [ ] Add the appropriate "cherry-pick" PR comment. See [Code Contribution](https://docs.asterisk.org/Development/Policies-and-Procedures/Code-Contribution/)

See:
https://docs.asterisk.org/Development/Policies-and-Procedures/Coding-Guidelines/
https://docs.asterisk.org/Development/Policies-and-Procedures/Code-Contribution/

**Review by gtjoseph — CHANGES_REQUESTED** [review]
@pitzkey Do you plan on addressing any of the issues mentioned?

**Comment by asteriskteam** [comment]
This PR has been marked stale because it has been in "Changes Requested" or "submitter-action-required" state for 28 days or more. Please make the requested changes within 14 days or the PR will be closed.

**Pull request closed without merging**
