### PR TITLE
README.md: Removed outdated link

### PR DESCRIPTION
**Pull request by shyjuk**
README.md: Removed outdated link http://www.quicknet.net

### CODE REVIEW

**Comment by InterLinked1** [comment]
CLA is not signed, and the commit message title does not follow commit message guidelines.

**Comment by shyjuk** [comment]
> CLA is not signed, and the commit message title does not follow commit message guidelines.

CLA Signed. Title changed.

**Review by gtjoseph — CHANGES_REQUESTED** [review]
Please add the appropriate "cherry-pick" comment to the PR.

See:
https://docs.asterisk.org/Development/Policies-and-Procedures/Coding-Guidelines/
https://docs.asterisk.org/Development/Policies-and-Procedures/Commit-Messages/

**Comment by shyjuk** [comment]
cherry-pick-to: 18, 20, 21 and master

**Review by shyjuk — COMMENTED** [review]
cherry-pick-to: 18, 20, 21 and master

**Comment by seanbright** [comment]
cherry-pick-to: 18
cherry-pick-to: 20
cherry-pick-to: 21

**Comment by seanbright** [comment]
@shyjuk read [step 5 on this page](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) and follow those instructions to re-request @gtjoseph's review.

**Review by jcolp — APPROVED** [review]

**Comment by seanbright** [comment]
@shyjuk you will need to squash your 2 commits in to 1.

**Comment by gtjoseph** [comment]
@shyjuk I'm afraid things are getting worse.  You've now got 3 commits in this PR, two of which aren't yours.  I think you need to start over with a clean, current checkout of master, create a new work branch off of it, make your change, commit and create a new PR.

I'm going to close this one.

**Pull request closed without merging**
