### PR TITLE
Carlb8 asterisk11.18 oauth2

### PR DESCRIPTION
**Pull request by chris001**
These are changes to enable oauth2 authentication for res_xmpp.c which is required for the xmpp connection to google, because sasl-plain text login to google is deprecated and disabled by default due to it being much less secure.
Original author of the res_xmpp.c changes was a sangoma employee, github/dslr/pbxinaflash user tm1000, he wrote it at an astricon, and compatibility fixes for asterisk 11 and 13, by dslr/github user carlb8. They all have gpl licensed their code, see the thread on dslr, see their posts on page 6-8 or so, out of 9 pages.
http://www.dslreports.com/forum/r30021383-Upgrade-Asterisk-to-an-OAUTH2-0-connection-with-Google-Voice~start=88

### CODE REVIEW

**Comment by chris001** [comment]
Would be great to fast-forward this res_xmpp oauth2 patch into asterisk 13.10+.
Also, you might want to activate travis-ci on github, and have it automatically test for errors...

**Comment by stgnet** [comment]
This repo is a mirror of our gerrit repository.  See  https://wiki.asterisk.org/wiki/display/AST/Patch+Contribution+Process for how to join the Asterisk development community there.

**Comment by jcolp** [comment]
As Scott mentioned we do not accept pull requests from Github, this is merely a mirror. All contributions have to be properly licensed and go through Gerrit for code review. As well we do have CI infrastructure over there which runs tests on contributions and Asterisk itself. The link Scott provided has details on what all is involved.

**Comment by chris001** [comment]
@jcolp @stgnet 
I read the digium contributor license agreement.
From the thread on DSLR, two guys who'd need to sign your digium contributor license agreement, are @tm1000 and @carlb8 
However carlb8 has already licensed it as GPLv3, and so has tm1000, as far as I know, having originally wrote it at astricon.
Would GPLv3 license alone be enough for you to take the pull request?
I suspect not because digium would want to include the GPL3 code in the commercial version of asterisk, is this accurate?

**Comment by jcolp** [comment]
@tm1000 already has signed the contributor license agreement. As for accepting it without signing the contributor license agreement only as a GPLv3 licensed code, that is correct - we could not.

**Pull request closed without merging**
