### PR TITLE
app_queue.c : fix "queue add member" usage string

### PR DESCRIPTION
**Pull request by Shaaah**
Fixing bracket placement in the "queue add member" cli usage string.

### CODE REVIEW

**Review by jcolp — APPROVED** [review]
Please add the appropriate cherry-pick-to comments per the documentation:

https://docs.asterisk.org/Development/Policies-and-Procedures/Code-Contribution/#create-a-pull-request

**Review by mbradeen — APPROVED** [review]

**Comment by InterLinked1** [comment]
> cherry-pick-to: 20 cherry-pick-to: 18

Is this not applicable to 21 as well?

**Comment by Shaaah** [comment]
It is! I updated my comment

**Comment by seanbright** [comment]
@Shaaah read [step 5 on this page](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) and follow those instuctions to re-request @gtjoseph's review.

**Review by gtjoseph — APPROVED** [review]

**Pull request merged**
