### PR TITLE
maximum_ms changed to multiple of 20

### PR DESCRIPTION
**Pull request by eduardomazolini**
The operator Vivo, the largest in Brazil, in its SIP service, fails to complete calls to Apple phones (iPhone) when the maxptime is not a multiple of 20. Rightly or wrongly, Vivo and Apple are giants and do not care to solve this problem. This is how I managed to solve the problem on my PBX.

### CODE REVIEW

**Comment by eduardomazolini** [comment]
[Jul 28 18:21:03] WARNING[4754]: asterisk.sipp:572 processEnded: b"2023-07-28t18:21:02.824998t1690568462.824998: Failed regexp match: looking in 'v=0rno=- 53655765 2353687639 IN IP4 127.0.0.1rns=Asteriskrnc=IN IP4 127.0.0.1rnt=0 0rnm=audio 18096 RTP/AVP 9 0 8 101rna=rtpmap:9 G722/8000rna=rtpmap:0 PCMU/8000rna=rtpmap:8 PCMA/8000rna=rtpmap:101 telephone-event/8000rna=fmtp:101 0-16rna=ptime:30rna=maxptime:140rna=sendrecvrn', with regexp 'a=maxptime:150+..*'n"

[Jul 28 18:21:03] WARNING[4754]: asterisk.sipp:572 processEnded: b"2023-07-28t18:21:02.840834t1690568462.840834: Failed regexp match: looking in 'v=0rno=- 53655765 2353687639 IN IP4 127.0.0.1rns=Asteriskrnc=IN IP4 127.0.0.1rnt=0 0rnm=audio 16860 RTP/AVP 9 101rna=rtpmap:9 G722/8000rna=rtpmap:101 telephone-event/8000rna=fmtp:101 0-16rna=ptime:40rna=maxptime:140rna=sendrecvrn', with regexp 'a=maxptime:150+..*'n"

[Jul 28 18:21:04] WARNING[4754]: asterisk.sipp:572 processEnded: b"2023-07-28t18:21:03.487622t1690568463.487622: Failed regexp match: looking in 'v=0rno=- 53655765 2353687639 IN IP4 127.0.0.1rns=Asteriskrnc=IN IP4 127.0.0.1rnt=0 0rnm=audio 19024 RTP/AVP 9 101rna=rtpmap:9 G722/8000rna=rtpmap:101 telephone-event/8000rna=fmtp:101 0-16rna=ptime:40rna=maxptime:140rna=sendrecvrn', with regexp 'a=maxptime:150+..*'n"

It failed because it succeeded in changing the maxptime, but the test regular expression expected the old value.

**Comment by eduardomazolini** [comment]
cherry-pick-to: 16
cherry-pick-to: 18
cherry-pick-to: 20

**Comment by eduardomazolini** [comment]
It failed because it succeeded in changing the maxptime, but the test regular expression expected the old value. Some revisor can help! Is very important for Brasilian users.

**Comment by InterLinked1** [comment]
> cherry-pick-to: 16 cherry-pick-to: 18 cherry-pick-to: 20

16 is not receiving bug fixes anymore, this would only be applicable to 18 and 20

> It failed because it succeeded in changing the maxptime, but the test regular expression expected the old value.

Any failing tests would also need to be updated

**Comment by eduardomazolini** [comment]
> The contributor license agreement has not yet been signed (you can see the link at the bottom of the checks list). Until that time this change can not be reviewed.

Done!

**Comment by eduardomazolini** [comment]
_answer/incoming/nominal/single-media-stream/audio/packetization [  19 of  133][Failed][  18][   1]
[Jul 28 18:21:03] WARNING[4754]: asterisk.sipp:572 processEnded: b"2023-07-28t18:21:02.824998t1690568462.824998: Failed regexp match: looking in 'v=0rno=- 53655765 2353687639 IN IP4 127.0.0.1rns=Asteriskrnc=IN IP4 127.0.0.1rnt=0 0rnm=audio 18096 RTP/AVP 9 0 8 101rna=rtpmap:9 G722/8000rna=rtpmap:0 PCMU/8000rna=rtpmap:8 PCMA/8000rna=rtpmap:101 telephone-event/8000rna=fmtp:101 0-16rna=ptime:30rna=maxptime:140rna=sendrecvrn', with regexp 'a=maxptime:150+..*'n"

That's not failure, it's intentional change with success. You can change the test regex to accept variable values.

**Comment by eduardomazolini** [comment]
> Any failing tests would also need to be updated

Why would it be essential for the maxptime to be 150. The flaw is because it was 140 and that's what I want, 140 is a multiple of 20. I might not agree with this need, but if you go to the forums, you'll see that everyone in Brazil has had problems with VIVO and the iPhone. As a result, the project becomes weak and many migrate to another solution. See log snippet "maxptime:140rna=sendrecvrn', with regexp 'a=maxptime:150+..*'"

**Comment by jcolp** [comment]
The testsuite is also on Github at https://github.com/asterisk/testsuite - it is expected that if test changes need to be done that they also be done alongside the patch by the contributor, otherwise someone else will have to get around to it when they can.

**Comment by eduardomazolini** [comment]
> The testsuite is also on Github at https://github.com/asterisk/testsuite - it is expected that if test changes need to be done that they also be done alongside the patch by the contributor, otherwise someone else will have to get around to it when they can.

Now I understand, I'm sorry I didn't. I didn't know the test was accessible to be edited. My forte is not regex, but I did my best. https://github.com/eduardomazolini/testsuite/pull/3

**Comment by eduardomazolini** [comment]
> The commit message is not following the commit message guidelines:
> 
> https://docs.asterisk.org/Development/Policies-and-Procedures/Commit-Messages

I understand the importance of clear commit messages. But I don't know exactly what I can rewrite. English is not my native language. Can you help me at this point to suggest the text and how can I edit it after it's written?
Thanks in advance for your patience in answering me.

**Comment by InterLinked1** [comment]
> > The commit message is not following the commit message guidelines:
> > https://docs.asterisk.org/Development/Policies-and-Procedures/Commit-Messages
> 
> I understand the importance of clear commit messages. But I don't know exactly what I can rewrite. English is not my native language. Can you help me at this point to suggest the text and how can I edit it after it's written? Thanks in advance for your patience in answering me.

Among other things:

- Commit message needs to be wrapped at 72 characters
- Title should be prefixed with the affected module or subsystem (e.g. codecs or codec_builtin)
- Title description should be capitalized and end in a period

The full commit guidelines contain all of these instructions and more.

As an example:

BAD

```
maximum_ms changed to multiple of 20
The operator Vivo, the largest in Brazil, in its SIP service, fails to complete calls to Apple phones (iPhone) when the maxptime is not a multiple of 20. Rightly or wrongly, Vivo and Apple are giants and do not care to solve this problem.
This is how I managed to solve the problem on my PBX.
```

BETTER:

```
codec_builtin: Use multiples of 20 for maximum_ms

Some providers require a multiple of 20 for the maxptime or fail to complete calls,
e.g. Vivo in Brazil. To increase compatibility, only multiples of 20 are now used.

Resolves: <issue num>
```

I don't see an open issue for this, which there should be as well, and referenced in the commit message.

**Review by eduardomazolini — COMMENTED** [review]
codec_builtin: Use multiples of 20 for maximum_ms

Some providers require a multiple of 20 for the maxptime or fail to complete calls,
e.g. Vivo in Brazil. To increase compatibility, only multiples of 20 are now used.

**Review by InterLinked1 — COMMENTED** [review]
A comment in the code itself as to why we need to use multiples of 20 would also be good, for people looking at this in the future, or if there are other compatibility concerns later on.

Only needed before the first change, e.g.

`/* For compatibility; some providers require maximum_ms to be a multiple of 20 */`

**Review by InterLinked1 — CHANGES_REQUESTED** [review]
Resolves: 260 should be Resolves: #260

**Comment by eduardomazolini** [comment]
> /* For compatibility; some providers require maximum_ms to be a multiple of 20 */

Done

**Review by jcolp — APPROVED** [review]

**Review by gtjoseph — CHANGES_REQUESTED** [review]
On hold pending testsuite changes.

**Comment by eduardomazolini** [comment]
> On hold pending testsuite changes.
> 

The testsuite change was approved.  But as it was done, the changes need to be simultaneous.

**Review by gtjoseph — APPROVED** [review]

**Comment by gtjoseph** [comment]
The testsuite changes merged so I'm running the cherry-pick tests again to make sure it passes.

**Pull request merged**
