### PR TITLE
menuselect: Use more specific error message.

### PR DESCRIPTION
**Pull request by InterLinked1**
Instead of using the same error message for
missing dependencies and conflicts, be specific
about what actually went wrong.

Resolves: #520

### CODE REVIEW

**Comment by InterLinked1** [comment]
cherry-pick-to: 18
cherry-pick-to: 20
cherry-pick-to: 21

**Review by jcolp — APPROVED** [review]

**Comment by miken32** [comment]
From a cosmetic POV this looks a bit messy with periods on a separate line:
```none

***********************************************************
  The existing menuselect.makeopts file did not specify    
  that 'res_pjsip_stir_shaken' should not be included.  However,              
  dependencies for this module were not found
  .
                                                           
  Either run 'make menuselect' or remove the existing      
  menuselect.makeopts file to resolve this issue.          
***********************************************************


***********************************************************
  The existing menuselect.makeopts file did not specify    
  that 'res_stir_shaken' should not be included.  However,              
  dependencies for this module were not found
  .
                                                           
  Either run 'make menuselect' or remove the existing      
  menuselect.makeopts file to resolve this issue.          
***********************************************************
```

(Detailing *which* library is missing [or, in this case, a wrong version] would be helpful, but I guess that's beyond the scope of this change.)

**Comment by InterLinked1** [comment]
> From a cosmetic POV this looks a bit messy with periods on a separate line:
> 
> ```
> 
> ***********************************************************
>   The existing menuselect.makeopts file did not specify    
>   that 'res_pjsip_stir_shaken' should not be included.  However,              
>   dependencies for this module were not found
>   .
>                                                            
>   Either run 'make menuselect' or remove the existing      
>   menuselect.makeopts file to resolve this issue.          
> ***********************************************************
> 
> 
> ***********************************************************
>   The existing menuselect.makeopts file did not specify    
>   that 'res_stir_shaken' should not be included.  However,              
>   dependencies for this module were not found
>   .
>                                                            
>   Either run 'make menuselect' or remove the existing      
>   menuselect.makeopts file to resolve this issue.          
> ***********************************************************
> ```
> 
> (Detailing _which_ library is missing [or, in this case, a wrong version] would be helpful, but I guess that's beyond the scope of this change.)

Yeah, that would be nice, though I wasn't really addressing that originally.
Also, the dependencies aren't necessarily libraries (they could be other modules, for example), but they are defined in the build system.

Do you find things to be more reasonable with a change like the following?

```
diff --git a/menuselect/menuselect.c b/menuselect/menuselect.c
index 222d0d79e5..8a8f23e615 100644
--- a/menuselect/menuselect.c
+++ b/menuselect/menuselect.c
@@ -1933,17 +1933,15 @@ static int sanity_check(void)
                                fprintf(stderr, "\n"
                                        "***********************************************************\n"
                                        "  The existing menuselect.makeopts file did not specify    \n"
-                                       "  that '%s' should not be included.  However,              \n"
-                                       "  %s%s\n"
-                                       "  %s.\n"
+                                       "  that '%s' should not be included.  However, %s%s%s\n"
                                        "                                                           \n"
                                        "  Either run 'make menuselect' or remove the existing      \n"
                                        "  menuselect.makeopts file to resolve this issue.          \n"
                                        "***********************************************************\n"
                                        "\n", mem->name,
-                                       mem->depsfailed ? "dependencies for this module were not found" : "",
+                                       mem->depsfailed ? "\ndependencies for this module were not found" : "",
                                        mem->depsfailed && mem->conflictsfailed ? " and" : "",
-                                       mem->conflictsfailed ? "a conflict exists" : "");
+                                       mem->conflictsfailed ? "\na conflict exists" : "");
                                insane = 1;
                        }
                }

```

**Comment by miken32** [comment]
Looks good, it was just the period on the newline made me wonder if there were *supposed* to be some details that were missing/empty for some reason.

**Comment by InterLinked1** [comment]
> Looks good, it was just the period on the newline made me wonder if there were _supposed_ to be some details that were missing/empty for some reason. I guess `However, %s%s%s.\n"` would work to keep the punctuation?

Yeah, good catch, there should be a period there!
I was mainly focused on the spacing between words originally and I guess the newline slipped my mind.
I'll take a look again and see if there's an easy way to have more detail, but if not, might just go ahead and put this up.

**Pull request merged**
